cc_library(
  name = 'src',
  warning = 'no',
  srcs = [
    'bignum.cc',
    'bignum-dtoa.cc',
    'cached-powers.cc',
    'diy-fp.cc',
    'double-conversion.cc',
    'fast-dtoa.cc',
    'fixed-dtoa.cc',
    'strtod.cc',
  ]
)
